name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code + LFS
      uses: actions/checkout@v3
      with:
        lfs: true  

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip setuptools

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install streamlit  

    - name: List installed packages
      run: pip list

    - name: Verify Python version
      run: python --version  

    - name: Debug environment (optional)
      run: |
        echo "Checking Python and pip versions..."
        python --version
        pip --version

    - name: Run tests
      run: python -m unittest discover -s tests -v