name: Python Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -v -p "test_*.py"
        
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --recursive=y src tests

  build-docs:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup MkDocs
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Build documentation
      run: |
        pip install mkdocs mkdocs-material
        mkdocs build --site-dir site